name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run tests
        run: yarn test
        env:
          BROWSER: ${{ github.event.inputs.browser }}

      - name: Store cucumber report
        run: bash report.sh

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh_pages
          PUBLISH_DIR: report-history

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-report
          path: report/
          retention-days: 30
