name: Playwright Docker Tests
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t playwright-docker

      - name: Run tests on docker image
        run: docker run -e BROWSER=${{ github.event.inputs.browser }} -v "$(pwd)":/app playwright-docker:latest sh -c "yarn install --frozen-lockfile && yarn test"

      - name: Run tests
        run: yarn test
        env:
          BROWSER: ${{ github.event.inputs.browser }}

      - uses: actions/upload-artifact@v4
        if: always()
        env:
          REPORT_NAME: Cucumber-Report-${{ github.run_id }}
        with:
          name: ${{ env.REPORT_NAME }}
          path: report/
          if-no-files-found: warn
          retention-days: 30
